# Generated by Django 6.1.1 on 2026-09-26 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('reino', models.CharField(max_length=80)),
                ('faccion', models.CharField(choices=[('alianza', 'Alianza'), ('horda', 'Horda')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nombre', 'reino'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'reino'), name='hermandad_nombre_reino_unico')],
            },
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('reino', models.CharField(max_length=80)),
                ('faccion', models.CharField(choices=[('alianza', 'Alianza'), ('horda', 'Horda')], max_length=10)),
                ('raza', models.CharField(max_length=80)),
                ('clase', models.CharField(choices=[('guerrero', 'Guerrero'), ('paladin', 'Paladín'), ('cazador', 'Cazador'), ('picaro', 'Pícaro'), ('sacerdote', 'Sacerdote'), ('chaman', 'Chamán'), ('mago', 'Mago'), ('brujo', 'Brujo'), ('monje', 'Monje'), ('druida', 'Druida'), ('caballero_muerte', 'Caballero de la Muerte'), ('cazador_demonios', 'Cazador de Demonios'), ('evocador', 'Evocador')], max_length=25)),
                ('especializacion', models.CharField(blank=True, max_length=80)),
                ('nivel', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('historia', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('hermandad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes', to='personajes.hermandad')),
            ],
            options={
                'ordering': ['-nivel', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('zona', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mision', 'Misión'), ('mazmorra', 'Mazmorra'), ('banda', 'Banda'), ('exploracion', 'Exploración'), ('pvp', 'JcJ')], max_length=12)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aventuras', to='personajes.personaje')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='personaje',
            constraint=models.UniqueConstraint(fields=('nombre', 'reino'), name='personaje_nombre_reino_unico'),
        ),
    ]
